### ISSUE TITLE
Support debug mode

### ISSUE THREAD

**Issue by moyui** [HenryQuan/WoWs-RS#11]
Hi, HenryQuan, I have done the following operation in the guide。but it doesn't work for me。so I want to de some testing，but I cann't find the 'debug' button。
Maybe the button is hidden deeply？Can you support the debug mode OR put the button on the visible area if possible。
The games version is 0.9.3.1 and using steam platform。
My apps and RS have been updating to the newest version already。

**Comment by HenryQuan** [comment]
You can try 1.0.5.5 version. Debug simply open the browser for you. There are too many reasons why it doesn't work. Please try enter the IP address with 8605 at the end in your browser and see if it shows anything (192.168.1.1 -> 192.168.1.1:8605).

**Comment by moyui** [comment]
我刚刚看到可以是中文....转圈圈成功之后好像我开一局游戏也没有显示，网页（移动端和电脑浏览器）测试过打开是个数组？ipad os 版本 13.4.1。我看1.0.5.5+版本上面是不让下载？https://github.com/HenryQuan/WoWs-RS/releases/tag/1.0.5.5 是这个版本对嘛

**Comment by HenryQuan** [comment]
是的。如果可以打开的话，应该就没有问题了。游戏replay功能需要打开，客户端会自动帮助打开的。1.0.5.5还在测试中但是应该没有问题。

**Comment by moyui** [comment]
补充：空数组。游戏配置文件（perferences）里面的replay是打开的，我重启了游戏再打开也还是不行。电脑端也已经用的是1.0.5.5.

**Comment by moyui** [comment]
看了之前的issue，发现我的replays目录下没有 tempArenaInfo.json这个文件？不知道现在还用不用这个配置去读了。replay结构现在是 ... World of Warships\replays\0.9.3.1\   这个文件夹下面我只看到有一个temp.wowsreplay

**Comment by HenryQuan** [comment]
可以把游戏目录截图一下么？还在replay文件夹的位置是在哪里呢？1.0.5.5版本认为replay文件夹在worldofwarships里面。

**Comment by moyui** [comment]
![image](https://user-images.githubusercontent.com/20638429/80913966-0d308980-8d7b-11ea-8093-940921eb5803.png)
![image](https://user-images.githubusercontent.com/20638429/80913975-1d486900-8d7b-11ea-819e-53e4659b51d6.png)
![image](https://user-images.githubusercontent.com/20638429/80913979-23d6e080-8d7b-11ea-8ce0-e7b609b6c747.png)

**Comment by moyui** [comment]
![image](https://user-images.githubusercontent.com/20638429/80913998-3cdf9180-8d7b-11ea-8fd6-875c4bdd0b52.png)
![image](https://user-images.githubusercontent.com/20638429/80914004-48cb5380-8d7b-11ea-9c93-e09fc5e14233.png)
![image](https://user-images.githubusercontent.com/20638429/80914013-51238e80-8d7b-11ea-898d-7119941bd568.png)

**Comment by moyui** [comment]
我想起来了，这个会和aslains里面的replay插件有关系吗？是不是文件路径被插件修改过了

**Comment by HenryQuan** [comment]
这个不太清楚但是replay文件夹的位置是正确的。可以试试进入训练房然后看replay文件夹里面是否有一个 .json文件（好像叫做temp arena）。

**Comment by moyui** [comment]
确认了，是aslains插件的锅，他把我的文件目录给改了，多谢作者帮忙排查，谢谢！节日快乐。

**Comment by HenryQuan** [comment]
没事没事，节日快乐。
话说插件把目录改成什么什么样了。replays里面有版本号么？这样的话我也许可以简单的向下搜索。目前还在制作新版本的app，之后会好好完善一下rs。

**Comment by moyui** [comment]
抱歉之后就没再看了，版本号我上图中的目录结构里有了，但是没有temparena.json的文件，可能还是在外层

**Comment by HenryQuan** [comment]
好的，多谢回复了。现在会开始改善一下旧版本。
