### ISSUE TITLE
这个游戏路径填什么内容

### ISSUE THREAD

**Issue by yuyuan1019** [HenryQuan/WoWs-RS#8]
![image](https://user-images.githubusercontent.com/32197442/68575404-f46ba900-04a6-11ea-98a3-73d0ea3d82a3.png)

**Comment by HenryQuan** [comment]
例如D:\Games\World_of_Warships （戰艦世界文件夾）

**Comment by yuyuan1019** [comment]
是不是不支持steam版的  我用steam的好像没用

**Comment by HenryQuan** [comment]
方便进入steamapps里面，截图给我看一样么？steam版确实没有测试过但是游戏里面应该是一样么。名字应该也不是World_of_Warships应该是类似D:\Games\Steam\steamapps\common\游戏名

**Comment by yuyuan1019** [comment]
![image](https://user-images.githubusercontent.com/32197442/68639255-eec1a200-053e-11ea-8d37-de13134193a3.png)
![image](https://user-images.githubusercontent.com/32197442/68639260-f1bc9280-053e-11ea-9a60-61328cac57c4.png)
![image](https://user-images.githubusercontent.com/32197442/68639263-f5501980-053e-11ea-89c9-e3125de6f709.png)

**Comment by HenryQuan** [comment]
十分感谢。WoWs RS是通过读取\replays\tempArenaInfo.json文件来实现的，所以如果replays文件夹存在的话，应该是可以正常是使用的。目前代码的检查是寻找exe程序，所以会说路径不正确，之后会修改一下。

**Comment by yuyuan1019** [comment]
谢谢

**Comment by yuyuan1019** [comment]
那我现在有解决方案吗 还是 先等着

**Comment by HenryQuan** [comment]
目前没有办法。但是我很快就写好了，应该更新一下就好了。

**Comment by HenryQuan** [comment]
https://github.com/HenryQuan/WoWs-RS/releases/tag/1.0.5.2
可以测试一下，但是不可以保证可以使用。

**Comment by yuyuan1019** [comment]
好的 ，我try try

**Comment by HenryQuan** [comment]
新版本可以正常使用么？

**Comment by yuyuan1019** [comment]
我家ip不是192.168.1.*的格式 好像也不行

**Comment by HenryQuan** [comment]
恩这样啊

**Comment by Exvoke** [comment]
你好 新版本的rs反而会提示错误的路径
但是我用了这个讨论串里面
https://github.com/HenryQuan/WoWs-RS/releases/tag/1.0.5.2
这个版本 好像可以正常使用
我是steam版的

**Comment by HenryQuan** [comment]
@Exvoke 我正在修复这个问题。因为steam版和普通版有一些不同，最近应该就会有更新。

**Comment by HenryQuan** [comment]
@Exvoke 你好，我上传了一个新的测试版（在release，1.0.5.5）。应该修复了这个错误。

**Comment by DarcyXv** [comment]
我连的学校的教育网，每次的ip是随机分配的，这个怎么解决呢。我是steam版的

**Comment by HenryQuan** [comment]
@DarcyXv 这样的话，只可以使用热点。

**Comment by DarcyXv** [comment]
害
    	
    	

    	获取 Outlook for iOS
    
  




On Thu, May 14, 2020 at 2:35 PM +0800, "Yiheng" <notifications@github.com> wrote:
















@DarcyXv 这样的话，只可以使用热点。
