### ISSUE TITLE
IOS13.3.1客户端实时功能报错

### ISSUE THREAD

**Issue by Schrscat** [HenryQuan/WoWs-RS#9]
RT
PC端已给管理员权限
但是就是没有办法显示
![IMG_1171](https://user-images.githubusercontent.com/27487511/75519026-4beb4180-59d0-11ea-80d9-264308b2d3fa.PNG)

**Comment by HenryQuan** [comment]
你好，目前正在修复这个问题。因为之前的版本是没有问题的，不知道发生了什么。

**Comment by HenryQuan** [comment]
你好，可以分别在电脑和手机浏览器里面打开这个[地址](http://192.168.2.18:8605)么？
我在我的IOS设备上测试了一下，然后发现是可以正常使用的。

**Comment by Schrscat** [comment]
> 你好，可以分别在电脑和手机浏览器里面打开这个[地址](http://192.168.2.18:8605)么？
> 我在我的IOS设备上测试了一下，然后发现是可以正常使用的。

sad

![93`TGT24QX3$1Z~(UNK9VZ6](https://user-images.githubusercontent.com/27487511/75610632-e470e700-5ae0-11ea-89ed-362fe8ff5770.png)

**Comment by Schrscat** [comment]
> 你好，可以分别在电脑和手机浏览器里面打开这个[地址](http://192.168.2.18:8605)么？
> 我在我的IOS设备上测试了一下，然后发现是可以正常使用的。

手机上也是不行的
我看了下PC上192.168.2.18:8605这个端口没有被占用
就很迷
![IMG_1186](https://user-images.githubusercontent.com/27487511/75611994-7e3e9100-5aed-11ea-9a13-69355085ebb1.PNG)

**Comment by HenryQuan** [comment]
那个rs软件里面显示的地址是192.168.2.18么？如果真的不行的话，可以使用手机热点。

**Comment by Schrscat** [comment]
> 那个rs软件里面显示的地址是192.168.2.18么？如果真的不行的话，可以使用手机热点。

是的，显示的是192.168.2.18

**Comment by HenryQuan** [comment]
那尝试一下热点呢？

**Comment by Schrscat** [comment]
> 那尝试一下热点呢？

sad
还是一样的

![IMG_1190](https://user-images.githubusercontent.com/27487511/75618145-ca162800-5b37-11ea-8563-1ae28c0ab5f6.PNG)
![IMG_1189](https://user-images.githubusercontent.com/27487511/75618146-caaebe80-5b37-11ea-8a93-e69e02209e9d.PNG)

**Comment by HenryQuan** [comment]
可是这个应该是成功了。不成功的话，是不会转圈圈的。

**Comment by moyui** [comment]
转圈圈成功之后好像我开一局游戏也没有显示，steam平台，游戏版本0.9.3.1。网页（移动端和电脑浏览器）测试过打开是个数组？ipad os 版本 13.4.1。不知道是不是哪里还有问题。

**Comment by jiangkh87** [comment]
您好，我也上不去了RS实时数据，请问怎么操作呢？

**Comment by jiangkh87** [comment]
![1](https://user-images.githubusercontent.com/65405935/82057770-6cd15200-96f6-11ea-9cd0-99346c9dfe56.png)

**Comment by HenryQuan** [comment]
@jiangkh87 可以发一个这个路径里面的文件和使用的客户端版本么？最新的版本会检查这个目录是否有 preference.xml 文件。之前的版本会检查worldofwarship.exe。

**Comment by jiangkh87** [comment]
您好，没问题我看下版本是Version 1.0.5<https://github.com/HenryQuan/WoWs-RS/releases/tag/1.0.5.1>

发件人: Yiheng <notifications@github.com>
发送时间: 2020年5月16日 9:50
收件人: HenryQuan/WoWs-RS <WoWs-RS@noreply.github.com>
抄送: jiangkh87 <jiangkh87@hotmail.com>; Mention <mention@noreply.github.com>
主题: Re: [HenryQuan/WoWs-RS] IOS13.3.1客户端实时功能报错 (#9)


@jiangkh87<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjiangkh87&data=02%7C01%7C%7Cca9412b160a04199574608d7f93b6d15%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637251905933477112&sdata=BjTFPaJC8yaJaX9m%2FJNFN%2Bsz9lCfsg2%2BRHB694i6W0U%3D&reserved=0> 可以发一个这个路径里面的文件和使用的客户端版本么？最新的版本会检查这个目录是否有 preference.xml 文件。之前的版本会检查worldofwarship.exe。

**Comment by jiangkh87** [comment]
您好，我的版本是Version 1.0.5

**Comment by jiangkh87** [comment]
wows的话是0.9.4版本，麻烦你了

**Comment by HenryQuan** [comment]
@jiangkh87 可以的话，可以先下载1.0.5.5版本。然后请发送一下preference.xml在什么位置，replay文件夹是否存在，是否使用mod。

**Comment by jiangkh87** [comment]
好的谢谢，1.0.5.5版本在哪里？

**Comment by HenryQuan** [comment]
@jiangkh87 在release里面，https://github.com/HenryQuan/WoWs-RS/releases。

**Comment by jiangkh87** [comment]
可以了谢谢，我是下1.0.5.2

**Comment by HenryQuan** [comment]
好的，这个问题我也先关闭了。目前大概知道客户端的问题。最近更新app之后，会重制改善一下客户端。
